//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerConceptDesign {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerConceptDesign.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Most listened.
        /// </summary>
        public static string HomePopular {
            get {
                return ResourceManager.GetString("HomePopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The last.
        /// </summary>
        public static string HomeTheLast {
            get {
                return ResourceManager.GetString("HomeTheLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Playlist.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MenuAnimation.
        /// </summary>
        public static string SettingsApplication {
            get {
                return ResourceManager.GetString("SettingsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blue.
        /// </summary>
        public static string SettingsBlue {
            get {
                return ResourceManager.GetString("SettingsBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на © Company.
        /// </summary>
        public static string SettingsCompany {
            get {
                return ResourceManager.GetString("SettingsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application was written for a course.
        /// </summary>
        public static string SettingsCompanyInfo1 {
            get {
                return ResourceManager.GetString("SettingsCompanyInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на project. All rights belong to the author..
        /// </summary>
        public static string SettingsCompanyInfo2 {
            get {
                return ResourceManager.GetString("SettingsCompanyInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        public static string SettingsContacts {
            get {
                return ResourceManager.GetString("SettingsContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email: dusya20032003@gmail.com.
        /// </summary>
        public static string SettingsContactsEmail {
            get {
                return ResourceManager.GetString("SettingsContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telegram: @sleepysad.
        /// </summary>
        public static string SettingsContactsTelegram {
            get {
                return ResourceManager.GetString("SettingsContactsTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string SettingsDark {
            get {
                return ResourceManager.GetString("SettingsDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string SettingsEnglish {
            get {
                return ResourceManager.GetString("SettingsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folder.
        /// </summary>
        public static string SettingsFolder {
            get {
                return ResourceManager.GetString("SettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open folder with music.
        /// </summary>
        public static string SettingsFolderInfo {
            get {
                return ResourceManager.GetString("SettingsFolderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string SettingsLight {
            get {
                return ResourceManager.GetString("SettingsLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu animation.
        /// </summary>
        public static string SettingsMenuAnimation {
            get {
                return ResourceManager.GetString("SettingsMenuAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set whether to animate the menu.
        /// </summary>
        public static string SettingsMenuAnimationInfo {
            get {
                return ResourceManager.GetString("SettingsMenuAnimationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Off.
        /// </summary>
        public static string SettingsOff {
            get {
                return ResourceManager.GetString("SettingsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        public static string SettingsOn {
            get {
                return ResourceManager.GetString("SettingsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Purple.
        /// </summary>
        public static string SettingsPurple {
            get {
                return ResourceManager.GetString("SettingsPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string SettingsRussian {
            get {
                return ResourceManager.GetString("SettingsRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silver.
        /// </summary>
        public static string SettingsSilver {
            get {
                return ResourceManager.GetString("SettingsSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size cover.
        /// </summary>
        public static string SettingsSizeCover {
            get {
                return ResourceManager.GetString("SettingsSizeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let cover size from 100 to 200 pixels.
        /// </summary>
        public static string SettingsSizeCoverInfo {
            get {
                return ResourceManager.GetString("SettingsSizeCoverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version 1.0.
        /// </summary>
        public static string SettingsVersion {
            get {
                return ResourceManager.GetString("SettingsVersion", resourceCulture);
            }
        }
    }
}
